#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFCD46_WebForm
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Configuration;
    using System.Data;
    using System.Data.Linq;
    using System.Data.Linq.Mapping;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Reflection;


    public partial class EmployeesDataContext : System.Data.Linq.DataContext
    {

        public EmployeesDataContext() :
                base(ConfigurationManager.ConnectionStrings["EduardoEmployeesConectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

    }
}
#pragma warning restore 1591
