<?xml version="1.0" encoding="utf-8"?><Database Name="EduardoEmployees" Class="EmployeesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.employees" Member="employees">
    <Type Name="employee">
      <Column Name="employee_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="hire_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="job_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="salary" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="manager_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="department_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="pwd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="employee_employee" Member="employees" ThisKey="employee_id" OtherKey="manager_id" Type="employee" />
      <Association Name="employee_employee" Member="employee1" ThisKey="manager_id" OtherKey="employee_id" Type="employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>